# Generated by Django 2.0.7 on 2018-07-26 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('owner_id', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(on_delete=False, related_name='likes', to='post.Post')),
            ],
        ),
    ]
